export default {
  light: {
    text: "#000",
    background: "#fff",
    tint: "#FF6B6B",
    tabIconDefault: "#ccc",
    tabIconSelected: "#FF6B6B",
    primary: "#FF6B6B",
    secondary: "#4ECDC4",
    success: "#4CAF50",
    warning: "#FFC107",
    danger: "#F44336",
    card: "#fff",
    border: "#e0e0e0",
  },
  dark: {
    text: "#fff",
    background: "#121212",
    tint: "#FF6B6B",
    tabIconDefault: "#666",
    tabIconSelected: "#FF6B6B",
    primary: "#FF6B6B",
    secondary: "#4ECDC4",
    success: "#4CAF50",
    warning: "#FFC107",
    danger: "#F44336",
    card: "#1e1e1e",
    border: "#333",
  },
};
